# 211939293
# kaganod

compile: bin
	javac -d bin -cp biuoop-1.4.jar src/*/*.java src/*.java
run:
	java -cp biuoop-1.4.jar:bin:resources Ass6Game 
jar:
	jar -cvfm ass6game.jar MANIFEST.MF -C bin . -C resources .
bin:
	mkdir bin
